apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: dev
  labels:
    app.kubernetes.io/name: demo
    service: demo
    app: demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-port
  selector:
    app.kubernetes.io/name: demo
    service: demo
    app: demo
  type: ClusterIP
