apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: dev
  labels:
    app.kubernetes.io/name: hello-world-app
    service: hello-world-app
    app: hello-world-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-port
  selector:
    app.kubernetes.io/name: hello-world-app
    service: hello-world-app
    app: hello-world-app
  type: ClusterIP
