apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-app
      service: hello-world-app
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
        app.kubernetes.io/name: hello-world-app
        service: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: gentitope/hello-world-app:IMAGE_TAG
          ports:
            - name: http-port
              containerPort: 5005
              protocol: TCP
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: hello-world-app-secret
                  key: MONGODB_URI
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: hello-world-app-configmap
                  key: DB_NAME
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /ping
              port: 5005
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /ping
              port: 5005
              scheme: HTTP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
