apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dev
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongodb-sa
      containers:
        - name: mongodb
          image: docker.io/mongo:4.2
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: adminpassword
          resources:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          ports:
            - name: mongodb-port
              containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi