apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-cr
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-crb
subjects:
  - kind: ServiceAccount
    name: mongodb-sa
    namespace: dev
roleRef:
  kind: ClusterRole
  name: mongodb-cr
  apiGroup: rbac.authorization.k8s.io