apiVersion: v1
kind: Service
metadata:
  name: mongodb-replica-0
  namespace: dev
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-0
  type: ClusterIP